version: '3.8'
services:
  backend:
    image: takiuddinahmed/honestelite-backend:latest
    ports:
      - "5000:3000"
    env_file:
      - backend.env
    networks:
      - app-network
    restart: on-failure
    volumes:
      - ./tmp:/tmp
  

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - app-network
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - app-network
    depends_on:
      - backend
  
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - prometheus
 
networks:
  app-network:
    driver: bridge
 
volumes:
  mongo_data: