version: '3.8'
services:
  backend:
    image: takiuddinahmed/honestelite-backend:latest
    ports:
      - "5000:3000"
    env_file:
      - .env
    networks:
      - app-network
    restart: on-failure
    volumes:
      - ./tmp:/tmp
      - ./backend:/app
  

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - app-network
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/:/prometheus
    ports:
      - '9090:9090'
    networks:
      - app-network
    depends_on:
      - backend


  
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
 
networks:
  app-network:
    driver: bridge
 
volumes:
  mongo_data:
  grafana-storage: